# Generated by Django 5.2.6 on 2025-09-15 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='newcontent',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300000),
        ),
    ]
